 var floatAge, floatDays, intWeeks, floatMonths, intFortnights;
     floatAge = parseFloat(prompt("Enter age in years"));
     floatDays = parseFloat(floatAge * 365.25);
     floatMonths = parseFloat(floatAge * 12);
     intWeeks = parseInt(floatDays / 7);
     intFortnights = parseInt(floatDays / 14);
     alert("Your age is: " + floatAge);
     alert("Age in Days: " + floatDays);
     alert("Age in Weeks: " + intWeeks);
     alert("Age in Months: " + floatMonths);
     alert("Age in Fortnights: " + intFortnights);